// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVP_XPEU5wYhu6bVD1q79mZH4ntOduBzc',
    appId: '1:527695276086:web:4a549e3ef291bfa0f11097',
    messagingSenderId: '527695276086',
    projectId: 'minilearn-4ff54',
    authDomain: 'minilearn-4ff54.firebaseapp.com',
    storageBucket: 'minilearn-4ff54.firebasestorage.app',
    measurementId: 'G-FEG8X812RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5W154OIDF_ZNL60lny0cGrAXT0vzk57M',
    appId: '1:527695276086:android:5e11dedc6431c797f11097',
    messagingSenderId: '527695276086',
    projectId: 'minilearn-4ff54',
    storageBucket: 'minilearn-4ff54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI7kILhrKmyvfAaMz28L6ComzPyZZiTUg',
    appId: '1:527695276086:ios:c05b7260382ffe9af11097',
    messagingSenderId: '527695276086',
    projectId: 'minilearn-4ff54',
    storageBucket: 'minilearn-4ff54.firebasestorage.app',
    iosClientId: '527695276086-1bmfeja5nj025u55vk9o9ov9c4hil2o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.minilearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI7kILhrKmyvfAaMz28L6ComzPyZZiTUg',
    appId: '1:527695276086:ios:c05b7260382ffe9af11097',
    messagingSenderId: '527695276086',
    projectId: 'minilearn-4ff54',
    storageBucket: 'minilearn-4ff54.firebasestorage.app',
    iosClientId: '527695276086-1bmfeja5nj025u55vk9o9ov9c4hil2o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.minilearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVP_XPEU5wYhu6bVD1q79mZH4ntOduBzc',
    appId: '1:527695276086:web:6a1f09287b58960ef11097',
    messagingSenderId: '527695276086',
    projectId: 'minilearn-4ff54',
    authDomain: 'minilearn-4ff54.firebaseapp.com',
    storageBucket: 'minilearn-4ff54.firebasestorage.app',
    measurementId: 'G-BGZ6RDE72Q',
  );
}
